wip: Paraview web
Azure/az-hop pull request #1344
Opened 2023-02-14 15:25 UTC by utkarshayachit

2023-02-21 19:39 UTC, utkarshayachit commented
@xpillions, this is ready for review. thanks.

2023-02-22 08:56 UTC, xpillons requested changes
Would it be possible to also automatically download an example during the installation ?

2023-02-22 08:56 UTC, xpillons commented on playbooks/roles/ood-applications/files/bc_vizer/form.yml.erb
> +    dataset_dir:
There is a way to allow a folder to be selected by the file explorer. Please have a look to the working_dir of the bc_codeserver app. You need to also add the form.js file

2023-02-22 12:39 UTC, utkarshayachit commented
> Would it be possible to also automatically download an example during the installation ?

done.

2023-02-22 12:40 UTC, utkarshayachit commented
@xpillions, I've made the updates. thanks.

2023-02-22 12:43 UTC, xpillons approved these changes

2023-02-22 13:56 UTC, utkarshayachit commented
thanks for the review!

2023-02-22 13:56 UTC, merged