Update index.md
Azure/az-hop pull request #1348
Opened 2023-02-15 21:34 UTC by sakinaalimsft

Addition of detailed instructions for how to install WSL as a prerequisite to toolchain configuration and other edits for clarity.

2023-02-15 21:35 UTC, sakinaalimsft commented
@microsoft-github-policy-service agree company="Microsoft"

2023-02-16 11:02 UTC, xpillons requested changes
please add the images too in the repo, not only the text.

2023-02-16 11:02 UTC, xpillons commented on docs/deploy/index.md
> + ![image](https://user-images.githubusercontent.com/119871043/219146537-14e9a00f-9c56-4f51-b566-e715e520cd2a.png)
Please make sure to add images as well in the repo and not outside

2023-02-22 00:31 UTC, sakinaalimsft commented
Made above changes to text to point to images in repo under azhop/docs/images as requested

2023-02-22 08:57 UTC, xpillons approved these changes

2023-02-22 08:57 UTC, merged